### ISSUE TITLE
Can't load LV2 plug-in in Carla: master_me_dsp.so is missing

### ISSUE THREAD

**Issue by unfa** [trummerschlunk/master_me#85]
Hi! I've just downloaded the 1.0.0 release package for Linux and I've symlinked the extracted `*.lv2` folders into my `~/.lv2`.
I've done a scan of plug-ins in Carla and tried to load master_me, but this was the result:

![image](https://user-images.githubusercontent.com/491704/188268605-12006d63-c552-4bb9-894c-7e3263050b16.png)

**Comment by falkTX** [comment]
this should be easy to check.. is the file there or not?

**Comment by unfa** [comment]
It is there:
![image](https://user-images.githubusercontent.com/491704/188270167-ba7b0c3c-4092-4154-b1c9-f1dd2cf1464d.png)

**Comment by unfa** [comment]
Interestingly Carla doesn't detect the VST3 plug-in either despite it clearly being in the search path:
![image](https://user-images.githubusercontent.com/491704/188270226-9c45324f-afa8-4260-a8f4-0c70e53b8a7f.png)
![image](https://user-images.githubusercontent.com/491704/188270235-c4698fef-a473-4912-8c77-dded35f23592.png)

**Comment by falkTX** [comment]
there seems to be a recent issue with python and symlinks.
try with real copy

**Comment by unfa** [comment]
Ok. Ardour can't load the VST3 plug-in either:
![image](https://user-images.githubusercontent.com/491704/188270356-fe597cd7-4c01-401d-b195-f89ae52327df.png)

**Comment by unfa** [comment]
Ardour also fails to load the LV2 plug-in:
```
2022-09-03T14:28:04 [ERROR]: LV2: Failed to instantiate plugin https://github.com/trummerschlunk/master_me
```

**Comment by falkTX** [comment]
An issue with how those links are created then?

**Comment by unfa** [comment]
I didn't do anything different from I always did and I never had issues. Plus other plug-ins linked the same way work fine.
Maybe it's a glibc issue of something like his?
I am on Arch Linux after all :thinking: 

I am thinking that because I cannot run the standalone version either:

```
unfa@unfa-desktop /d/S/m/master_me-1.0.0> ./master_me
exec: Failed to execute process: '/data/Software/master_me/master_me-1.0.0/master_me' the file could not be run by the operating system.
```

```
unfa@unfa-desktop /d/S/m/master_me-1.0.0 [126]> file ./master_me
./master_me: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=a4de656595e21eea1d329b17a134a5641ba78728, for GNU/Linux 3.7.0, stripped
```

**Comment by falkTX** [comment]
wow, this is really the first time I see such an issue.. no idea what is happening here. maybe your glibc is so new old binaries no longer work at all?

might be best to go with the aur package for now

**Comment by unfa** [comment]
Oh, I didn't know there was one. I'll try it now.

**Comment by unfa** [comment]
It seems it depends on `faust` but the PKGBUILD doesn't specify it so the build fails. Installing `faust` now and I'll try again...

**Comment by unfa** [comment]
Ok, looks like that didn't do the trick:

```
==> Sources are ready.
==> Making package: master_me 1.0.0-2 (sob, 3 wrz 2022, 23:02:58)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting build()...
mkdir -p bin/master_me.lv2
faustpp -Dbinary_name="master_me" -Dbrand="Klaus Scheuermann" -Dhomepage="https://4ohm.de/" -Dlabel="master_me" -Dlicense="GPLv3+" -Dlicenseurl="http://spdx.org/licenses/GPL-3.0-or-later.html" -Dlibext=".so" -Dlv2uri="https://github.com/trummerschlunk/master_me" -Dversion_major=1 -Dversion_minor=0 -Dversion_micro=0 -Duitype=X11 -a template/LV2/manifest.ttl master_me.dsp -o bin/master_me.lv2/manifest.ttl
ERROR in seq() expressions. The iterated function must have the same number of inputs and outputs. Here (0 : !),(_<:_,(_,(_,1 : @) : +)) has 1 inputs and 2 outputs
Traceback (most recent call last):
  File "/usr/bin/faustpp", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/faustpp/main.py", line 42, in main
    mdresult: FaustResult = call_faust(cmd.dspfile, mdargs)
  File "/usr/lib/python3.10/site-packages/faustpp/call_faust.py", line 89, in call_faust
    proc.check_returncode()
  File "/usr/lib/python3.10/subprocess.py", line 456, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['faust', '-O', '/tmp/tmpv86xqqyg', '-o', 'master_me.dsp.cpp', '-xml', 'master_me.dsp', '-a', '/tmp/tmpv37m6iko.cpp']' returned non-zero exit status 1.
make: *** [Makefile:166: bin/master_me.lv2/manifest.ttl] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: master_me

```

**Comment by falkTX** [comment]
that is a faust related issue now. @sletz any ideas?

**Comment by sletz** [comment]
Indeed ! @orlarey one of last commit is breaking here

**Comment by trummerschlunk** [comment]
On my arch linux, the 1.0.0 release runs without problems. Copied the files. No symlinks.
![master_me ardour](https://user-images.githubusercontent.com/19374731/188592075-d5878a03-f3f5-49b2-a6a8-dd5ebebee045.png)
![master_me bitwig](https://user-images.githubusercontent.com/19374731/188592107-1cab3823-6f19-4e2d-84da-4cbe1248dab7.png)
![master_me carla](https://user-images.githubusercontent.com/19374731/188592127-93ba7aca-69e3-4ad3-8849-7aef1030a5fe.png)

**Comment by orlarey** [comment]
> Indeed ! @orlarey one of last commit is breaking here

In a previous commit, the seq(I, N, foo) construction was made stricter, expecting foo to have the same number of inputs and outputs. That's not the case in the master_me code (probably one of the imported libraries). To make the code compile again, I have relaxed this constraint in the last commit of Faust 0bb74e58e5ca9d9eea03ba3b1f53f9f7d08d162a. We will probably make that stricter version of seq optional instead.

**Comment by trummerschlunk** [comment]
@unfa did you manage to run the plugin on your system?

**Comment by falkTX** [comment]
closing due to inactivity
