### ISSUE TITLE
Can't build on Debian Bullseye

### ISSUE THREAD

**Issue by trebmuh** [trummerschlunk/master_me#91]
```
Compiling src/ApplicationPrivateData.cpp
master_me.dsp : 485 : ERROR : undefined symbol : onePoleSwitching
Traceback (most recent call last):
  File "/usr/bin/faustpp", line 33, in <module>
    sys.exit(load_entry_point('faustpp==1.0.0', 'console_scripts', 'faustpp')())
  File "/usr/lib/python3/dist-packages/faustpp/main.py", line 43, in main
    mdresult: FaustResult = call_faust(cmd.dspfile, mdargs)
  File "/usr/lib/python3/dist-packages/faustpp/call_faust.py", line 89, in call_faust
    proc.check_returncode()
  File "/usr/lib/python3.9/subprocess.py", line 460, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['faust', '-O', '/tmp/tmpxqvhue4o', '-o', 'master_me.dsp.cpp', '-xml', 'master_me.dsp', '-a', '/tmp/tmpjnnbaoae.cpp']' returned non-zero exit status 1.
master_me.dsp : 485 : ERROR : undefined symbol : onePoleSwitching
Traceback (most recent call last):
  File "/usr/bin/faustpp", line 33, in <module>
    sys.exit(load_entry_point('faustpp==1.0.0', 'console_scripts', 'faustpp')())
  File "/usr/lib/python3/dist-packages/faustpp/main.py", line 43, in main
    mdresult: FaustResult = call_faust(cmd.dspfile, mdargs)
  File "/usr/lib/python3/dist-packages/faustpp/call_faust.py", line 89, in call_faust
    proc.check_returncode()
  File "/usr/lib/python3.9/subprocess.py", line 460, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['faust', '-O', '/tmp/tmp79usc_0t', '-o', 'master_me.dsp.cpp', '-xml', 'master_me.dsp', '-a', '/tmp/tmpx07bt22j.cpp']' returned non-zero exit status 1.
make[2]: *** [Makefile:167: bin/master_me.lv2/ui.ttl] Error 1
make[2]: *** Waiting for unfinished jobs....
Compiling src/Color.cpp
make[2]: *** [Makefile:167: bin/master_me.lv2/plugin.ttl] Error 1
Compiling src/EventHandlers.cpp
master_me.dsp : 485 : ERROR : undefined symbol : onePoleSwitching
Traceback (most recent call last):
  File "/usr/bin/faustpp", line 33, in <module>
    sys.exit(load_entry_point('faustpp==1.0.0', 'console_scripts', 'faustpp')())
  File "/usr/lib/python3/dist-packages/faustpp/main.py", line 43, in main
    mdresult: FaustResult = call_faust(cmd.dspfile, mdargs)
  File "/usr/lib/python3/dist-packages/faustpp/call_faust.py", line 89, in call_faust
    proc.check_returncode()
  File "/usr/lib/python3.9/subprocess.py", line 460, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['faust', '-O', '/tmp/tmpmj7xwhfu', '-o', 'master_me.dsp.cpp', '-xml', 'master_me.dsp', '-a', '/tmp/tmpxi8m29rg.cpp']' returned non-zero exit status 1.
make[2]: *** [Makefile:167: bin/master_me.lv2/manifest.ttl] Error 1
```

Let me know if I can provide any more useful information

**Comment by falkTX** [comment]
That is normal, master_me requires a more up to date faust version than debian stable provides.

**Comment by trebmuh** [comment]
Thanks for the quick answer.
What is the minimal version needed?

**Comment by falkTX** [comment]
I am not 100% sure, but I know the version in Ubuntu 22.04 was not enough either, which is 2.37
Right now I have 2.41.1 which works, so it is something in between those.

**Comment by falkTX** [comment]
btw, it is a totally doable to pregenerate the faust files and place them on the repo, thus skipping both faustpp and faust dependency.
Takes more time for project maintenance, in case faust file change we need to manually regen things, but makes it easier for packagers...

@trummerschlunk what do you think?

**Comment by trummerschlunk** [comment]
Sounds more autonomous and stable to me. If you are for it, I'm in :)

**Comment by falkTX** [comment]
@trebmuh try with latest git, faust should no longer be needed to build.
if you need a source tarball, just wait for CI to complete in the actions tab, there will be a source-tar artifact there.

**Comment by magnetophon** [comment]
@falkTX Thanks, that made it much easier to package for NixOS.
We don't have faustpp yet.

**Comment by trebmuh** [comment]
_I forgot to update this issue._

Thanks for the advice @falktx. It works as expected.
